[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
homepage = "https://github.com/rust-cli/anstyle"
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.64.0"  # MSRV
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "benches/**/*",
  "examples/**/*"
]
