[package]
name = "anstyle-yansi"
version = "0.3.0"
description = "Adapt between yansi and anstyle"
repository = "https://github.com/rust-cli/anstyle.git"
homepage.workspace = true
categories.workspace = true
keywords = ["ansi", "terminal", "color", "yansi"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/rust-cli/anstyle/compare/{{tag_name}}...HEAD", exactly=1},
]


[dependencies]
anstyle = { version = "0.3.0", path = "../anstyle" }
yansi = "0.5.1"
